# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Tests CI

on:
  pull_request:
    branches: [main]

jobs:
  test-cdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.2
          cache: 'yarn'
      - name: Install all dependencies
        run: yarn install
      - name: Run tests on lib
        working-directory: ./cdk-scheduler
        run: yarn test
      - name: Build library
        working-directory: ./cdk-scheduler
        run: yarn build
      - name: Run tests on gateway demo 
        working-directory: ./demo/apiGatewayIntegration
        run: yarn test
      - name: Run tests on lambda demo 
        working-directory: ./demo/lambdaIntegration
        run: yarn test

